{{- $vm_operator := index .Values "victoria-metrics-operator" }}
{{- if $vm_operator.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ printf "%s-%s" (include "victoria-metrics-k8s-stack.fullname" $) "operator" | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ default $.Release.Name $.Values.argocdReleaseOverride | quote }}
      app.kubernetes.io/name: victoria-metrics-operator
{{- if empty $vm_operator.operator.vmServiceScrape.spec }}
  endpoints:
  - port: "http"
{{ else }}
{{- if not (hasKey $vm_operator.operator.vmServiceScrape.spec "endpoints") }}
  endpoints:
  - port: "http"
{{- end }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
{{ omit $vm_operator.operator.vmServiceScrape.spec "selector" "namespaceSelector" | toYaml | indent 2 }}
{{- end }}
{{- end }}
